### ISSUE TITLE
Pop-Out Screenshare is broken.

### ISSUE THREAD

**Issue by Charcadet** [powercord-org/powercord#447] opened 2021-01-14 15:48 UTC
**Describe the bug**
When you press the "Pop-Out" button in a voicechat where someone is screensharing, the pop out window will show however their screen share will permanently load.

**To Reproduce**
Get into a server voicechat with a friend
Have the friend turn on screensharing
Use the "Pop-Out" button on the bottom right
See how the screen share will just permanently try to load with no success 

**Expected behavior**
Screenshare to load.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 64bit
 - Powercord version: fada35c v2

**Additional context**
 - [X] I checked if Discord and/or Powercord are up to date
 - [X] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment] 2021-01-14 16:01
Duplicate of #378

**Closed as completed by cyyynthia** 2021-01-14 16:01 UTC
Labels: bug, duplicate
