### ISSUE TITLE
[Feature Request] Fix wayland screen sharing because upstream won't

### ISSUE THREAD

**Issue by reesericci** [powercord-org/powercord#606] opened 2022-01-10 16:58 UTC
**Describe the feature request**
A clear and concise description of what the feature is.
It would be really cool if powercord could fix screen sharing on Wayland. (Linux)
**What Plugin would it be for?**
Name of plugin if applicable

**Expected behavior**
Discord screenshares via pipewire and the screencast xdg portal

**Comment by cyyynthia** [comment] 2022-01-10 16:59
Duplicate of #555

**Closed as completed by cyyynthia** 2022-01-10 16:59 UTC
Labels: duplicate

**Comment by reesericci** [comment] 2022-01-10 17:01
wow that was fast
