### ISSUE TITLE
after update it won't load

### ISSUE THREAD

**Issue by Space-Clustercompany** [powercord-org/powercord#541] opened 2021-08-27 01:35 UTC
**Describe the bug**
after discord update discord refused to conteneo loading after i lunch it and just crashes

**To Reproduce**
1-update to the latest version
2-start discord 

**Expected behavior**
it crashing

**Desktop (please complete the following information):**
 - OS: winds
 -  - Powercord version:i can't get it duo to discord crashing

**Additional context**
 - [yup] I checked if Discord and/or Powercord are up to date
 - [yup] I made sure this is not related to an external plugin or a theme

**Comment by JustAnOkapi** [comment] 2021-08-27 01:54
running:
`npm i`
`npm run unplug`
`npm run plug`
also does not fix the problem
the powercord devs have to make a patch before this will be fixed.

**Comment by cyyynthia** [comment] 2021-08-27 02:07
Cannot reproduce on latest (Linux, Canary 95131 (8577a57), Host 0.0.127). Either this is a platform-specific issue, or an issue caused by a plugin in which case this is **not** a Powercord problem.

**Comment by SisterVersio** [comment] 2021-08-27 02:10
this can be reproduced on a completely clean reinstall of both powercord and canary as of a very recent update to canary, this is definitely affecting windows users if not linux

**Comment by JustAnOkapi** [comment] 2021-08-27 02:15
> Cannot reproduce on latest (Linux, Canary 95131 (8577a57), Host 0.0.127). Either this is a platform-specific issue, or an issue caused by a plugin in which case this is **not** a Powercord problem.

I cannot recreate on linux but a fresh install of powercord on windows still crashes

**Comment by cyyynthia** [comment] 2021-08-27 02:27
I experimented locally and issued a possible hotfix in dad99e2 - let me know if it solves the issue

**Comment by JustAnOkapi** [comment] 2021-08-27 02:28
> I experimented locally and issued a possible hotfix in [dad99e2](https://github.com/powercord-org/powercord/commit/dad99e245e211a6acee0b5ddb88f4e54f9aabee3) - let me know if it solves the issue

FIXED!
updating fixed the crash

**Comment by BenSegal855** [comment] 2021-08-27 02:30
> I experimented locally and issued a possible hotfix in [dad99e2](https://github.com/powercord-org/powercord/commit/dad99e245e211a6acee0b5ddb88f4e54f9aabee3) - let me know if it solves the issue

Fixed.
Powercord: dad99e2
Canary: 8577a57

**Closed as completed** 2021-08-27 02:30 UTC
Labels: bug
