### ISSUE TITLE
[Translator] Error translating big messages.

### ISSUE THREAD

**Issue by SacreBleuXCVII** [powercord-org/powercord#71] opened 2019-01-16 20:32 UTC
**Describe the bug**
Unable to translate big messages.

**To Reproduce**
- Find or send a message with over 1500 characters.
- Try to translate it.

**Expected behavior**
Message should be translated.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Discord version: [BUILD INFO] Release Channel: canary, Build Number: 30945

**Additional context**
Error message in console: `Uncaught (in promise) TypeError: Cannot create property 'headers' on string`

**Comment by cyyynthia** [comment] 2019-01-16 20:44
This is fixed here https://github.com/aetheryx/powercord/tree/experimental-stable-ptb, so the issue is gonna be closed when it gets merged to v2

**Closed as completed** 2019-01-26 17:47 UTC
Labels: bug
