### ISSUE TITLE
CSS bug

### ISSUE THREAD

**Issue by Lizzy284** [powercord-org/powercord#374] opened 2020-08-05 19:46 UTC
**Describe the bug**
when i go into the quickCSS settings sometimes the "close" button is fiddly and you have to be in the right place to close it
**To Reproduce**
DiscordSettings>Themes>quickCSS>detach it>open settings>try to close it
**Expected behavior**
should be able to close without issue
**Desktop (please complete the following information):**
 - OS: Windows
 - Powercord version: [You can find it in the Updater tab, available in your settings]
[i think this is right] 0.0.266
**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date yes
 - [x] I made sure this is not related to an external plugin or a theme; yes

**Comment by cyyynthia** [comment] 2020-08-11 17:54
Cannot reproduce. Unsure about what's going on there

**Comment by cyyynthia** [comment] 2020-09-25 12:17
This should have been fixed in latest versions; lmk if it's not the case

**Closed as completed by cyyynthia** 2020-09-25 12:17 UTC
Labels: bug
