### ISSUE TITLE
High outbound packet loss

### ISSUE THREAD

**Issue by CodingArctic-zz** [powercord-org/powercord#448] opened 2021-01-15 03:46 UTC
**Describe the bug**
When using powercord and talking in a voice channel my outbound packet loss rate spikes to up to 30% very often. It's not my wifi, and my friends don't hear any difference in my audio quality, its just really weird and annoying. I've looked it up and the thing that fixed most people's clients with the same issue was completely reinstalling, so I'm thinking its an issue with the modifications powercord does.

**To Reproduce**
Have powercord, talk in a vc when looking at the voice debug stats

**Expected behavior**
Packet loss should be around 0% as I have no internet issues. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Powercord version: v2 fada35c

**Additional context**
 - [ X ] I checked if Discord and/or Powercord are up to date
 - [ X ] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment] 2021-01-15 10:24
Powercord doesn't modify anything related to the network nor to the voice engine altogether, so this shouldn't happen. Does the packet drops happen in spikes (if yes, spikes of regular or irregular intervals?), or is continuous? Which third-party plugins do you have installed (if any)?

**Comment by CodingArctic-zz** [comment] 2021-01-15 14:58
Hi, I was just talking about this in #misc-support in the discord yesterday. The spikes only happen when I start talking, and I've tried reinstalling discord like other support outlets have said.

**Comment by hypermug1** [comment] 2021-05-22 20:53
I've reproduced according to how you described and the packet loss has not spiked. You sure this is not related your network or device specs?
`Tested on Ubuntu 20.04.2 LTS x86_64 `
I apologize if this was not very helpful.

**Comment by cyyynthia** [comment] 2021-08-10 16:20
Closing due to the lack of input

**Closed as completed by cyyynthia** 2021-08-10 16:20 UTC
Labels: bug, need more info
