### ISSUE TITLE
pc-codeblocks Occasionally crashed discord.

### ISSUE THREAD

**Issue by GavynStanley** [powercord-org/powercord#421] opened 2020-10-30 23:30 UTC
**Describe the bug**
I opened discord, and loading took a bit. Then I couldn't see any servers and then my discord crashed. I only started getting this today, and does it occasionally. I used github filter to search for a duplicate of this and didn't find one. Sorry if there is one.
![Image](https://i.adiscorduser.com/e1e1XHp.png)

**To Reproduce**
I simply opened up discord.

**Expected behavior**
Not crash

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19041)
 - Powercord version: Powercord v2 (d02006e)

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment] 2020-10-30 23:31
Duplicate of #367, this is the same underlying cause.

**Closed as completed by cyyynthia** 2020-10-30 23:31 UTC
Labels: bug, duplicate
