### ISSUE TITLE
powercord bootlooping

### ISSUE THREAD

**Issue by SeeGreatness** [powercord-org/powercord#452] opened 2021-01-28 05:45 UTC
I am not sure how to give any more information other than the latest version has caused it to boot loop, is there a log file I can post to find more information about my problem?

**Comment by cyyynthia** [comment] 2021-01-28 11:20
Duplicate of #450 

Please see [this comment](https://github.com/powercord-org/powercord/issues/450#issuecomment-768311167) for the procedure to follow.

**Closed as completed by cyyynthia** 2021-01-28 11:20 UTC
Labels: bug, duplicate
