### ISSUE TITLE
Crash when typing in command

### ISSUE THREAD

**Issue by dweam** [powercord-org/powercord#277] opened 2020-01-24 23:28 UTC
**Describe the bug**
The discord client will [crash](https://cdn.discordapp.com/attachments/493218587037794324/670405162170580992/unknown.png) whenever typing in any command

**To Reproduce**
1. Switch locale to either Japanese or Turkish
2. Start typing a command, ie: `.heygirl`, it should crash.

**Expected behavior**
Not crash and be able to run the command

**Desktop (please complete the following information):**
 - OS: Gentoo Linux, Kernel: 4.19.97-Gentoo-X86_64
 - Discord and Powercord version: "Release Channel: canary - Discord's Build Number: 53218 - Powercord's git revision: 5488d8b2063fee9d7327f79d194e9fea3779c201@v2"

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme -- (running fresh install)
 
**Add any other context about the problem here.**
Custom prefix (seems?) to put it into a crash loop.

**Comment by GriefMoDz** [comment] 2020-01-25 01:00
Cannot reproduce; client doesn't crash, let alone dive into a "crash loop" when inputting an available command using a custom or default prefix.

*All tests for custom were preformed using a single (`'!'`), a double (`'->'`), and a triple character (`'pc-'`) prefix.*

OS: `Windows 8.1 - Version 9600 (Build 6.3.9600)`
Discord version*:
- `Release Channel: canary - Discord's Build Number: 53218 - Powercord's git revision: ed5de5a45cac402876ae171255760f947cdccf9e@v2-dev`
- `Release Channel: stable - Discord's Build Number: 53202 - Powercord's git revision: 5488d8b2063fee9d7327f79d194e9fea3779c201@v2`

*Multiple Discord installations (i.e. `canary` and `stable`).

**Comment by cyyynthia** [comment] 2020-01-25 11:37
Can reproduce. Happens with Japanese locale (maybe others, didn't checked them all)

**Comment by dweam** [comment] 2020-01-25 16:04
It seems to only happen with Japanese and Turkish locales after going through all of the locales.
Turkish crashes with the same [error](https://cdn.discordapp.com/attachments/579644208260972556/670660000733069312/unknown.png) as Japanese

**Comment by cyyynthia** [comment] 2020-01-25 16:09
Thanks for checking all that! Can you also confirm that Japanese locale messes up Font Awesome icons? Might as well fix it
![](https://epic.weeb.services/᠎‌%E2%80%8B%E2%81%A0‌%E2%80%8B‍%E2%80%8B)

**Comment by dweam** [comment] 2020-01-25 16:17
Can confirm. The font issue also occurs on the following:

- Korean
- Taiwanese
- Chinese

**Comment by cyyynthia** [comment] 2020-01-25 17:10
A fix has been rolled out to development branch 🎉 
Since that bug is rather specific it won't be merged immediately in stable branch

**Closed as completed** 2020-01-30 23:26 UTC
Labels: bug
