### ISSUE TITLE
Unable to uninstall built-in modules

### ISSUE THREAD

**Issue by Martmists-GH** [powercord-org/powercord#414] opened 2020-10-18 23:50 UTC
```js
768d939f2b18f33f1fd6.js:16 Uncaught TypeError: this.onUninstall is not a function
    at onClick (/home/mart/git/powercord/src/Powercord/plugins/pc-moduleManager/components/parts/BaseProduct.jsx:62)
    at Object.E (b492c55ac526a5f85915.js:78)
    at I (b492c55ac526a5f85915.js:78)
    at b492c55ac526a5f85915.js:78
    at O (b492c55ac526a5f85915.js:78)
    at L (b492c55ac526a5f85915.js:78)
    at N (b492c55ac526a5f85915.js:78)
    at C (b492c55ac526a5f85915.js:78)
    at On (b492c55ac526a5f85915.js:78)
    at ce (b492c55ac526a5f85915.js:78)
    at Dn (b492c55ac526a5f85915.js:78)
    at Mn (b492c55ac526a5f85915.js:78)
    at Pn (b492c55ac526a5f85915.js:78)
    at t.unstable_runWithPriority (b492c55ac526a5f85915.js:86)
    at zi (b492c55ac526a5f85915.js:78)
    at fu (b492c55ac526a5f85915.js:78)
    at Ln (b492c55ac526a5f85915.js:78)
    at HTMLDocument.r (768d939f2b18f33f1fd6.js:16)
```

**Comment by GavynStanley** [comment] 2020-10-19 01:58
Known issue https://github.com/powercord-org/powercord/issues/332

**Comment by cyyynthia** [comment] 2020-10-19 12:48
Duplicate of #332

**Closed as completed by cyyynthia** 2020-10-19 12:48 UTC
Labels: bug, duplicate
