### ISSUE TITLE
short description of bug

### ISSUE THREAD

**Issue by JacquesHumule** [powercord-org/powercord#513] opened 2021-06-12 12:35 UTC
**Describe the bug**
Icon in settings are too big
![image](https://user-images.githubusercontent.com/32205945/121776077-4432ba80-cb8b-11eb-81db-75e2527e2e1a.png)

**To Reproduce**
 It does that since the last update

**Expected behavior**
Icon must be smaller

**Desktop (please complete the following information):**
 - OS: Windows
 - Powercord version:  f876037

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment] 2021-06-12 12:36
Related/duplicate of #512

**Closed as completed by cyyynthia** 2021-06-12 12:36 UTC
Labels: duplicate
