### ISSUE TITLE
[Feature Request] Updater - Display update info on the update screen

### ISSUE THREAD

**Issue by devoxin** [powercord-org/powercord#162] opened 2019-04-13 19:48 UTC
**Describe the feature request**
When checking for updates from the `Updater` menu, the install options should display on the same page (if an update is available).
I believe this would be a more convenient (and expected) location for update options to show, and would be convenient as the blank space can be used for showing a changelog if/when one is implemented also.

![](https://its-called-hentai-and-its.art/67fd5e7b8a.png)

**What Plugin would it be for?**
Updater.

**Expected behavior**
Update install options should be displayed on the same screen when checking for updates from the `Updater` menu.

**Comment by cyyynthia** [comment] 2019-04-13 19:50
Duplicate of #120, this will get addressed in #155

**Comment by devoxin** [comment] 2019-04-13 20:18
I wouldn't say this is a duplicate as this issue addresses what I would consider a consistency issue; where you'd expect update options to be shown on the `Updater` page, but are still shown in the pop-up modal instead

**Comment by cyyynthia** [comment] 2019-04-13 20:23
So a comparaison would be the windows update screen, with everything on it?

Also note that we'll add transparent update mode for plugin and themes by default, and (opt-in) version for Powercord's core, and automatically reload when you're considered as away by Discord (or by clicking a small button like Discord update button)

**Comment by devoxin** [comment] 2019-04-13 20:30
yea, similar to a windows update screen. So when the Updater settings screen is visible (as seen in the screenshot above), the small modal wouldn't appear at the bottom right of the screen; instead you'd be present with the normal options on the settings screen such as
`Update now`
`Update later`

The other two options probably wouldn't be needed as the settings page can be dismissed simply by pressing ESC or via the close button.

**Comment by cyyynthia** [comment] 2019-09-10 21:04
To group everything related to Updater updates, i made a global issue available here #230, so discussions/tracking will continue there

**Closed as completed by cyyynthia** 2019-09-10 21:04 UTC
Labels: enhancement
