### ISSUE TITLE
Discord won't launch

### ISSUE THREAD

**Issue by Ectalite** [powercord-org/powercord#441] opened 2021-01-08 08:31 UTC
**Describe the bug**
Discord canary won't launch since last update.

**To Reproduce**
1) install last version of discord canary for macOS
2) `npm run plug` (successfully plugged)
3) See discord not launching (no window is opening)

**Expected behavior**
Discord launch and normal behavior of discord.
Discord was working before plugging.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Powercord version: last from git

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme (I just have a theme and I don't think it can be related)
 
I just launched Discord this morning and it updated itself. Before the update everything was fine.

**Comment by kwvg** [comment] 2021-01-08 12:50
Thought something was wrong on my end or it was Powercord that was broken, didn't even consider that it might've been Discord Canary breaking things!

**Comment by oliver-ni** [comment] 2021-01-08 20:22
Having the same issue on macOS

**Comment by dvtkrlbs** [comment] 2021-01-09 08:12
I am having the same issue on macos too

**Comment by ia74** [comment] 2021-01-09 18:20
I am also having the same issue

**Comment by GriefMoDz** [comment] 2021-01-10 07:32
As a bit of a follow up to this issue, I've just released a hotfix that "*should*" prevent Discord from no longer launching while Powercord is injected. Seeing as this is an attempt to remediate the problem and isn't necessarily something final, I've also decided to leave this open until further notice in the brisk chances that it still remains valid.

I'd greatly appreciate it if you could let us know that it's working for you by either posting a message under the "#powercord-core" channel on our Discord server, or by simply reacting with a "👍🏼" on this comment. Thank you!

**Comment by GriefMoDz** [comment] 2021-01-11 05:00
Based on the feedback I've received from the majority of Mac users in the Powercord server, I can confirm that this has since been resolved as of https://github.com/powercord-org/powercord/commit/fada35c3171e8544077e90d5a621120c8a3eca53.

If you're still unable to launch Discord, please ensure that Powercord is up-to-date by navigating to your current install in a terminal and running the following the command: `npm run unplug && git pull && npm run plug`. Once this command has been successfully executed you'll need to restart Discord via the means of the system tray or task manager.

That said, I'll now be closing this issue. If you have any questions or concerns, please feel free to reach out to our team on the [Powercord server](https://discord.gg/gs4ZMbBfCh). Thanks!

**Closed as completed by GriefMoDz** 2021-01-11 05:00 UTC
Labels: bug
