### ISSUE TITLE
Create In showing incorrect modal

### ISSUE THREAD

**Issue by dhanrahl** [powercord-org/powercord#361] opened 2020-07-19 20:04 UTC
**Describe the bug**
When adding an emote via right-click menu "Create In", it pops up an incomplete Streaming modal instead.

**To Reproduce**
Attempt to add any emote via right-click menu.

**Expected behavior**
Should open the emote modal

**Desktop (please complete the following information):**
 - OS: Windows 10 v1909 Build: 18363.959
 - Powercord version: f8180d3

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment] 2020-07-19 20:06
Duplicate of #360 
This has been fixed in dev branch, however we're not rolling out to stable yet due to other issues in the dev branch

**Closed as completed by cyyynthia** 2020-07-19 20:06 UTC
Labels: bug
