### ISSUE TITLE
Plugins Dont Get Removed

### ISSUE THREAD

**Issue by Lizzy284** [powercord-org/powercord#387] opened 2020-09-07 17:59 UTC
**Describe the bug**
when you go into plugins and try to delete any plugin it doesnt work, you can reload, restart, do whatever it will not be removed
**To Reproduce**
settings>plugins> try to delete a plugin and it wont work
**Expected behavior**
plugin to be deleted and removed
**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows
 - Powercord version: [You can find it in the Updater tab, available in your settings]
41cb7ce
**Additional context**
 - [yes ] I checked if Discord and/or Powercord are up to date
 - [ yes ] I made sure this is not related to an external plugin or a theme

**Comment by Juby210** [comment] 2020-09-07 18:00
duplicate of #332

**Closed as completed** 2020-09-07 18:04 UTC
Labels: duplicate
