### ISSUE TITLE
[Bug] Powercord Settings are broken.

### ISSUE THREAD

**Issue by CorellanStoma** [powercord-org/powercord#627] opened 2022-04-19 12:01 UTC
**Describe the bug**
It seems that the settings in Powercord are broken. Settings, plugins, themes have no text and the updater and settings page do not work at all. The plugin and theme page seem to work, but apparently buttons also have no text.

**To Reproduce**
hmm no idea how to reproduce it, since it occurs even with a new installation.

**Expected behavior**
The settings should normally work.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.22000)
 - Powercord version: b4103b0
 - Discord: Canary 124608 (ee90752) | Host 1.0.46

**Additional context**
 - [ ✓] I checked if Discord and/or Powercord are up to date
 - [ ✓ ] I made sure this is not related to an external plugin or a theme
 - [ ✓] I used a fresh Discord Canary + Powercord Installation
 
 ![image](https://user-images.githubusercontent.com/58918358/163998422-a0e1bbbc-3721-4ad4-9497-7e0df2ec66f8.png)
![image](https://user-images.githubusercontent.com/58918358/163998380-874879fa-c869-4584-9c71-612fe66334ac.png)
![image](https://user-images.githubusercontent.com/58918358/163998397-7a7b8007-1b53-4925-bc2c-19f09caa7eb2.png)
![image](https://user-images.githubusercontent.com/58918358/163998487-e10193e6-dfb5-4f6e-a890-0779f2129e49.png)
![image](https://user-images.githubusercontent.com/58918358/163998652-c366fb34-43f8-4a24-8152-d9bc3d9e0a98.png)
![image](https://user-images.githubusercontent.com/58918358/163998678-4fe05a6a-6ae4-4099-a1fc-48f4b570e291.png)

**Comment by CorellanStoma** [comment] 2022-04-19 12:14
![image](https://user-images.githubusercontent.com/58918358/164000847-ce9371bb-af5d-49b1-89cd-4e2e333001c7.png)

**Comment by JaceThings** [comment] 2022-04-19 12:14
Same thing here with OSX
![image](https://user-images.githubusercontent.com/60551230/164000973-83763ddb-9ea5-4c17-bfcd-a6c68b372aab.png)

Edit: This is also a bug I found lol
<img width="139" alt="Bred Screenshot Number 001879@2x" src="https://user-images.githubusercontent.com/60551230/164001760-4652ee46-cec6-4b23-b206-c03f5bb85c4f.png">

**Comment by kamuro-cho** [comment] 2022-04-19 13:00
i have the same issue, although had toasts and other pop-ups be blank (themself, and buttons, as mentioned in the issue itself)
using windows 11 instead of 10, however.
i will try getting a screenshot of the blank pop-ups, toasts and buttons when i encounter that once more

**Comment by kritishd8** [comment] 2022-04-19 16:23
![image](https://user-images.githubusercontent.com/69711181/164050313-fc80aa88-69d9-4017-9af3-0326c04c9d82.png)
the issue doesn't exist on linux tho :+1:

**Comment by Archhon** [comment] 2022-04-19 19:37
Most likely and issue with an update inside the original Discord or something.

**Comment by tazz4843** [comment] 2022-04-19 22:36
> the issue doesn't exist on linux tho 👍

I can actually reproduce on Linux Mint 20.3
```
Canary 124757 (f2acbc2) Host 0.0.135 Linux 64-Bit (5.4.0-107-Generic)Powercord v2 (b4103b0)
```

**Comment by owocado** [comment] 2022-04-20 03:55
I have the same issue on arch linux on Canary 124831 (9040dfd)

**Comment by kritishd8** [comment] 2022-04-20 05:46
weird because discord canary has already updated twice after i commented here and i still dont have the issue.

**Comment by CorellanStoma** [comment] 2022-04-20 06:30
When I change the language from **English, UK** to **English, US** it's fixed in Powercord, but after a reload or restart everything is as before. This can be tested with basically any language.

![image](https://user-images.githubusercontent.com/58918358/164164531-5a993618-d1d3-4c96-a44f-a375918de602.png)
![image](https://user-images.githubusercontent.com/58918358/164164538-37239338-c43a-4c2a-ac45-cf635bc2606a.png)

**Comment by JOJOVAV** [comment] 2022-04-21 09:24
changing discord language does do the trick, but when you restart the bug is the same. In my case when I restart discord(ctrl + r)
I get the same bug but when reloading the little tips are in my language(dutch) instead of english (my discord is in english).
edit: putting my discord in my language does the trick for not having that bug again.

**Comment by kritishd8** [comment] 2022-04-21 12:45
yea this is weird af, so on my ubuntu based linux theres no problem but then on my arch linux this problem existed but then again after reinstall it was fixed in my arch and just few hours ago when i tested this in my friends computer with windows 11 there was no issue

**Comment by SwitchAlpha** [comment] 2022-04-21 20:49
Changing language from English(UK) to English(US) worked for me too

**Comment by JaceThings** [comment] 2022-04-22 11:45
> Changing language from English(UK) to English(US) worked for me too

This worked for me 😳

**Closed as completed** 2022-04-23 21:55 UTC
Labels: bug
